#!/bin/sh
set -e
if [ "$1" = "remove" ] || [ "$1" = "purge" ]; then
    rm -rf /opt/openbot/venv
fi
if [ "$1" = "purge" ]; then
    rm -rf /var/lib/openbot
    deluser --system openbot >/dev/null 2>&1 || true
fi
exit 0
